services:
  barkeep.laravel.prod:
    image: 'defconfive/barkeep:latest'
    ports:
      - '${APP_PORT:-80}:80'
    configs:
      - source: barkeep.laravel.env
        target: /var/www/html/.env
    secrets:
      - barkeep.secrets
    volumes:
      - '.:/var/www/html'
    networks:
      - barkeep
    healthcheck:
      test: ['CMD', 'php', '/var/www/html/artisan', 'octane:status']
    depends_on:
      - pgsql
  barkeep.pgsql:
    image: 'postgres:17.4-alpine3.21'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    configs:
      - source: barkeep.pgsql.env
    secrets:
      - barkeep.secrets
    volumes:
      - 'barkeep-pgsql:/var/lib/postgresql/data'
    networks:
      - barkeep
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
      retries: 3
      timeout: 5s
networks:
  barkeep:
    driver: bridge
volumes:
  barkeep-storage:
    driver: local
  barkeep-pgsql:
    driver: local
secrets:
  barkeep.secrets:
    external: true
configs:
  barkeep.laravel.env:
    external: true
  barkeep.pgsql.env:
    external: true
